<?php

/**
 * @file
 *
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_internet_archive_bookreader_menu() {
  return array(
    'admin/islandora/internet_archive_bookreader' => array(
      'title' => 'Internet Archive BookReader',
      'description' => 'Configure the Internet Archive BookReader.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_internet_archive_bookreader_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'islandora_bookreader.admin.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'internet_archive_bookreader_ocr/%islandora_object' => array(
      'page callback' => 'islandora_internet_archive_bookreader_get_page_ocr',
      'page arguments' => array(2),
      'access callback' => 'islandora_object_access_callback',
      'access arguments' => array(FEDORA_VIEW, 2),
      'file' => 'includes/ocr.callback.inc',
      'type' => MENU_CALLBACK,
    ),
    'internet_archive_bookreader_search/%/%' => array(
      'page callback' => 'islandora_internet_archive_bookreader_search',
      'page arguments' => array(1, 2),
      'access callback' => 'user_access',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'includes/search.callback.inc',
      'type' => MENU_CALLBACK,
    )
  );
}

/**
 * Implements hook_theme().
 */
function islandora_internet_archive_bookreader_theme() {
  return array(
    'islandora_internet_archive_bookreader' => array(
      'file' => 'theme/islandora_bookreader.theme.inc',
      'template' => 'theme/islandora-internet-archive-bookreader',
      'variables' => array(
        'object' => NULL,
        'page_progression' => 'lr',
        'pages' => array(),
        'height' => 960,
        'width' => 600
      )
    ),
    'islandora_internet_archive_bookreader_book_info' => array(
      'file' => 'theme/islandora_internet_archive_bookreader.theme.inc',
      'variables' => array('object' => NULL),
    )
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_internet_archive_bookreader_islandora_viewer_info() {
  return array(
    'islandora_internet_archive_bookreader' => array(
      'label' => t('Internet Archive BookReader'),
      'description' => t('Internet Archive BookReader.'),
      'configuration' => 'admin/islandora/internet_archive_bookreader',
      'callback' => 'islandora_internet_archive_bookreader_viewer_callback',
      'model' => array('islandora:iabookCModel'),
    ),
  );
}

/**
 * Callback function for the viewer.
 *
 * @param string $uri
 *  Image url be passed to the viewer.
 *
 * @return string
 *  HTML repersentation of the OpenSeadragon viewer
 */
function islandora_internet_archive_bookreader_viewer_callback(array $params) {
  return theme('islandora_bookviewer_internet_archive_bookreader', $params);
}
