<?php




/**
 * @file
 * Configuration module for islandora_solr_search.module
 */

/**
 * Implements hook_islandora_solr_primary_display()
 */
function islandora_bookviewer_search_islandora_solr_primary_display() {
  return array(   
    'islandora_bookviewer' => array(
      'name' => t('Bookviewer Results'),
      'module' => 'islandora_bookviewer_search',
      'file' => 'BookviewerSolrResults.inc',
      'class' => "BookviewerSolrResults",
      'function' => "displayResults",
      'description' => t("A simple tabular output"),
    ),
  );
}

/**
 * Implementation of hook_help()
 */
function islandora_bookviewer_search_help($path, $arg) {

  switch ($path) {
    case 'admin/help#islandora_solr_config':
      return t("When 'Sample Solr Configuration Settings' is selected from the configuration drop-down in the<br />
        !page the following settings will be used.
        <ul>
        <li>Module - islandora_bookviewer_search</l1>
        <li>File - BookviewerSolrResults.inc</l1>
        <li>Class - BookviewerSolrResults</l1>
        <li>Method - displayResults</l1>
        </ul>
        ", array('!page' => l("Islandora_solr_search configuration page", 'admin/settings/islandora_solr_search'),)
      );
  }
}

